CREATE TABLE new_begginers(
id BIGINT NOT NULL AUTO_INCREMENT,
title VARCHAR(255) NOT NULL,
description TEXT,
difficult VARCHAR(50),
completed BOOLEAN DEFAULT FALSE,
tips TEXT,
category VARCHAR(50),
start TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);